package model.entities;

import java.util.Date;
import java.util.Objects;

import enums.JobRoles;

public class Employee {
	
	private Integer id;
	private String name;
	private Double salary;
	private Date contractDate;
	private char gender;
	private JobRoles role;
	private Department department;
	
	public Employee () {
		
	}
	
	//The ID will be null when instantiating the object. 
	//It will be generated by the Database, and set on its insert.
	public Employee(Integer id, String name, Double salary, Date contractDate, char gender, JobRoles role, Department department) {
		this.id = id;
		this.name = name;
		this.salary = salary;
		this.contractDate = contractDate;
		this.gender = gender;
		this.role = role;
		this.department = department;
	}
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getSalary() {
		return salary;
	}

	public void setSalary(Double salary) {
		this.salary = salary;
	}

	public Date getContractDate() {
		return contractDate;
	}

	public void setContractDate(Date contractDate) {
		this.contractDate = contractDate;
	}

	public char getGender() {
		return gender;
	}

	public void setGender(char gender) {
		this.gender = gender;
	}

	public JobRoles getRole() {
		return role;
	}

	public void setRole(JobRoles role) {
		this.role = role;
	}

	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	@Override
	public int hashCode() {
		return Objects.hash(id);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Employee other = (Employee) obj;
		return Objects.equals(id, other.id);
	}

	@Override
	public String toString() {
		return "Employee [id=" + id + ", name=" + name + ", salary=" + salary + ", contractDate=" + contractDate
				+ ", gender=" + gender + ", role=" + role + ", department=" + department + "]";
	}

	
	
	
	
	

	
}
